---
title: "tydir 101"
author: "Clémence HUANG"
format: html
editor: visual
---

```{r}
#| message: false
here::i_am("dm-course-git-101-hc.Rproj")
library(here)
```

```{r}
#| message: false
library(ggplot2)
library(dplyr)
library(tidyr)
```

```{r}
data("EuStockMarkets")
```

## Displaying one time series

```{r}
ggplot(EuStockMarkets, aes(x=time(EuStockMarkets), y=DAX)) +
  geom_line()
```

```{r}
EuStockMarkets <- 
  EuStockMarkets |> 
    as_tibble() |>  ## could be as.data.frame
    mutate(date = as.numeric(time(EuStockMarkets)))
```

```{r}
ggplot(EuStockMarkets, aes(x=date, y=DAX)) +
  geom_line()
```

```{r}
ggplot(EuStockMarkets, aes(x=date, y=CAC)) +
  geom_line()
```

## Two indexes on the same graphical representation ?

### Poor man's solution

```{r}
ggplot(EuStockMarkets, aes(x=date, y=CAC)) +
  geom_line(colour = "steelblue") +
  geom_line(mapping=aes(y=DAX), colour = "salmon")
```

### Tidyr solution

```{r}
EuStockMarkets |>
  pivot_longer(!date, names_to = "index") |>
  slice_head(n=10) |>
  knitr::kable()
```

```{r}
EuStockMarkets |>
  pivot_longer(!date, names_to = "index") |>
  ggplot(aes(x=date, y=value, colour=index)) +
  geom_line()
```
# More pivoting
```{r}
EuStockMarkets |>
  pivot_longer(!date,names_to="index") |>
  slice_head(n=10) |>
  knitr::kable()
```

```{r}
EuStockMarkets |>
  pivot_longer(DAX|SMI) |>
  slice_head(n=10) |>
  knitr::kable()
```
## Rendering on rows
```{r}
EuStockMarkets |>
  select(!FTSE) |>
  pivot_longer(!date) |> slice_head(n=10)
```

```{r}
EuStockMarkets |>
  select(!FTSE) |>
  pivot_longer(!date) |> 
  summarize(avg_stock = mean(value),.by = date) |>
  slice_head(n=10) |>
  knitr::kable()
```

Alternative `rowwise`
```{r}
EuStockMarkets |>
  select(!FTSE) |>
  rowwise() |>
  summarise(date,avg_stock = mean(DAX,SMI,CAC))
```

## Reverse operation : pivot to a wider format
```{r}
EuLong <-
  EuStockMarkets |>
  pivot_longer(!date)
```

```{r}
EuLong |>
  pivot_wider() |>
  slice_head(n=10) |>
  knitr::kable()
```

```{r}
EuLong |>
  pivot_wider(id_cols=date)
```

```{r}
data("diamonds")
```

```{r}
dgroup <-
  diamonds |>
  summarise(count=n(),median_price = median(price),.by=c(cut,color))
```

```{r}
dgroup |>
  select(!count) |> # here do not need select because specifying one column
  pivot_wider(id_cols = cut,names_from = color, values_from = median_price)
```

